### ISSUE TITLE
Conjured Sweet Roll (level 45 conjured bread) is not recognized as a food.

### ISSUE THREAD

**Issue by flexd** [Beast-Masters-addons/feed-o-matic#10]
Like title says, the addon does not recognise this as a food, but I can feed my pet (spawn of hakkar) just fine with it. He gains 35 happiness from it.

https://classic.wowhead.com/item=8076/conjured-sweet-roll

**Comment by datagutten** [comment]
What is this pet's diet, and which category should this be put in? I can add it, but I need to know where to put it so the addon does not try to feed it to a pet that doesn't like it.

**Comment by flexd** [comment]
I don't have wow in front of me right now, but it eats bread, cheese and fish. It's a wing serpent. A very common pet, it's one of the three best ones we can have until Zul Gurub opens and the stronger pet in there is also a wing serpent (Son of Hakkar)

**Comment by Usul420** [comment]
Yes it is a Bread. still not accepting this as a valid food.
https://classic.wowhead.com/item=8076/conjured-sweet-roll
