### ISSUE TITLE
Hunter’s Helper

### ISSUE THREAD

**Issue by Tntdruid** [Beast-Masters-addons/feed-o-matic#11]
Do you have any plans to make http://fizzwidget.com/hunters-helper-discontinued/ work in WoW classic?

**Comment by datagutten** [comment]
I have looked at it, but I did not understand what it can be used for.
Is it so that taming a new pet learns you abilities which can be used by existing pets?
I will download the old source and see if I can make it run on classic so I can see how it works.

**Comment by Tntdruid** [comment]
You can see pet skills you can get from mobs before you tame then, you get a tooltip whit the skill.

Better info here https://www.wowinterface.com/downloads/info4072-FizzwidgetHuntersHelper.html

**Comment by datagutten** [comment]
I started working on it now, but it is not easy. This addon has not been updated for many years and there is a lot of changes in the API and lua calls.

**Comment by flexd** [comment]
> I have looked at it, but I did not understand what it can be used for.
> Is it so that taming a new pet learns you abilities which can be used by existing pets?
> I will download the old source and see if I can make it run on classic so I can see how it works.

This is how learning new ranks of pet skills work, in case you were unaware. You tame a pet that has a higher rank skill, use the pet a bit, and then you can teach that skill to other pets that have lower ranks version of it. (I.e to those that are compatible. You can't teach   prowl to a owl and so on)

**Comment by datagutten** [comment]
After a lot of work, I finally managed to fix all obvious bugs and released a stable version for WoW classic here: https://github.com/Beast-Masters-addons/HuntersHelper
I have played WoW since this skill system was live, but I can't remember this part. I probably played with my bear with its standard skills and never thought about learning new skills.

**Comment by Tntdruid** [comment]
@datagutten Thanks so much you rock! 👍
