### ISSUE TITLE
multiple bugs

### ISSUE THREAD

**Issue by WoWEye** [Beast-Masters-addons/feed-o-matic#18]
upon login I get  the following errors.  I DO NOT cook (alts do that for me)  but that never use to matter. 
Also it does not show up in the Interface for addon settings NOR does it show the button in which to feed it. Just the yellow frowny face.
Date: 2021-11-01 22:30:36
ID: -3
Error occurred in: Global
Count: 1
Message: ..\AddOns\GFW_FeedOMatic\FOM_CookingScan.lua line 7:
   attempt to index field 'professions' (a nil value)
Debug:
   [string "@GFW_FeedOMatic\FOM_CookingScan.lua"]:7: in main chunk
Locals:
_ = "GFW_FeedOMatic"
addon = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'professions' (a nil value)"

- - ALSO
Date: 2021-11-01 22:30:36
ID: -1
Error occured in: Global
Count: 1
Message: [string "Frame_GFW_FeedOMatic:OnLoad"] line 1:
   attempt to call global 'FOM_OnLoad' (a nil value)
Debug:
   [string "*:OnLoad"]:1:
      [string "*:OnLoad"]:1
Locals:
self = Frame_GFW_FeedOMatic {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = Frame_GFW_FeedOMatic {
 0 = <userdata>
}
(*temporary) = "attempt to call global 'FOM_OnLoad' (a nil value)"

AND
Date: 2021-11-01 22:30:36
ID: -2
Error occured in: Global
Count: 1
Message: ..\AddOns\GFW_FeedOMatic\FeedOMatic.lua line 11:
   attempt to index field 'utils' (a nil value)
Debug:
   [string "@GFW_FeedOMatic\FeedOMatic.lua"]:11: in main chunk
Locals:
addonName = "GFW_FeedOMatic"
addon = <table> {
}
tableUtils = nil
utils = nil
GetPetFoodTypes = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'utils' (a nil value)"

**Comment by datagutten** [comment]
It seems like you got a build without the required dependencies and that the addon is trying to reference them. You probably got an error from LibStub saying that the libraries are not found. I am adding some extra checks now to make clearer error messages if dependencies are not found and for next the build I will verify that all dependencies are correctly added.
