### ISSUE TITLE
Links to this github and additional author recognition 

### ISSUE THREAD

**Issue by b-morgan** [Beast-Masters-addons/feed-o-matic#20]
I suggest that you add a link (or more) to the documentation and source files (where appropriate) pointing to this GitHub. You might also add your name as an author in appropriate places as well.

**Comment by datagutten** [comment]
I have added a link to the toc file, but I don't like to add author information header to all source files.

**Comment by b-morgan** [comment]
Maybe just add you name as an author in the toc file(s).
