### ISSUE TITLE
update for classic?

### ISSUE THREAD

**Issue by amey1956** [Beast-Masters-addons/feed-o-matic#22]
anniversary server fom not working - if anyone is updating
`2x GFW_FeedOMatic/FeedOMatic.lua:905: CreateFrame(): Couldn't find inherited node "OptionsBoxTemplate"
[string "=[C]"]: in function `CreateFrame'
[string "@GFW_FeedOMatic/FeedOMatic.lua"]:905: in function `FOM_BuildFoodsUI'
[string "@GFW_FeedOMatic/FeedOMatic.lua"]:1397: in function `SetupOptions'
[string "@GFW_FeedOMatic/FeedOMatic.lua"]:1421: in function <GFW_FeedOMatic/FeedOMatic.lua:1407>
[string "=[C]"]: ?
[string "@Questie/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ceQuestie/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Questie/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Questie/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...ceQuestie/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
(*temporary) = "Frame"
(*temporary) = "FOM_FoodListBorder"
(*temporary) = Frame {
 obj = <table> {
 }
 name = "GFW Feed-O-Matic"
}
(*temporary) = "OptionsBoxTemplate"
`

**Comment by amey1956** [comment]
anyone out there checking in?

**Comment by datagutten** [comment]
I tried to fix this now, but the addon still has a lot of bugs due to outdated code, which I am working to replace.
