### ISSUE TITLE
Replace food tables with LibPeriodicTables

### ISSUE THREAD

**Issue by datagutten** [Beast-Masters-addons/feed-o-matic#5]
Check if [LibPeriodicTable](https://www.curseforge.com/wow/addons/libperiodictable-3-1) can be used to get food types instead of maintaining the tables in this addon.

**Comment by ShaunaGordon** [comment]
He had specifically switched away from it, so you'll want to look at https://github.com/fizzwidget/feed-o-matic/search?q=periodic&unscoped_q=periodic&type=Code and see if his reasons for switching away from it still apply.

**Comment by datagutten** [comment]
There is no reliable source for food types, according to https://github.com/fizzwidget/feed-o-matic/issues/2 LibPeriodicTable and other issue this addon was the only one using this information from LibPeriodicTable.
I will try to maintain the list in this addon and add some kind of crowd-sourcing the information.
