### ISSUE TITLE
Create a project on CurseForge or WoWInterface so we can see updates

### ISSUE THREAD

**Issue by b-morgan** [Beast-Masters-addons/feed-o-matic#6]
I check for updates regularly on CurseForge (actually Twitch client) and WoWInterface (I also maintain addons on both sites). I believe it would be useful if you used one of these two sites just to house the .zip file (that is how my addons are on WoWInterface).

I was/am a big fan of Fizzwidget's addons and I'm very happy to see this one for Classic. Keep up the good work!

**Comment by datagutten** [comment]
CurseForge has a license selection and a review process which I am not sure if it will pass. The original owner has not explicitly specified an open-source license or allowed me to redistribute it.
I am currently reworking the classic implementation, and when it is done I will make an attempt to upload it there.
Uploading the zip is no problem, the packaging script I use supports automatic upload to both sites.

**Comment by ShaunaGordon** [comment]
It won't pass CurseForge's license review (I tried). They consider Fizz's stuff "All Rights Reserved" and without proof of permission, will deny the project request.

> Uploading the zip is no problem, the packaging script I use supports automatic upload to both sites.

CurseForge and I think WoWI, too, has issues with the "one zip, two versions" thing. The "best practice" way is generally accepted to be the BigWigs script (or similar packager) to create two zips and have it upload them. (The Twitch app apparently still struggles a bit with the whole "multiple versions of WoW" thing in general.)

**Comment by Tntdruid** [comment]
I made a link here https://www.wowinterface.com/downloads/fileinfo.php?id=4160#comments

Thanks for making it work again!

**Comment by datagutten** [comment]
The addon is published on WowInterface: https://www.wowinterface.com/downloads/info25427-Feed-O-Matic.html
